# Copyright 2018 REMME
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

version: '2.1'

services:
  remme-docs:
    build: ..
    image: remme/remme-core:latest
    volumes:
      - ..:/root/remme
      - ../README.rst:/root/remme/docs/README.rst
    ports:
      - '${REMME_DOCS_SERVER_PORT:-8000}:8000'
    env_file:
      - ../.env
    entrypoint: |
      bash -c "
        sphinx-autobuild -H 0.0.0.0 -p 8000 remme/docs remme/docs/html
      "
